version: '3'

services:
  www:
    image: lsfiege/shawnweb:latest
    container_name: www
    restart: always
    tty: true
    ports:
      - 8888:80
    depends_on:
      - db
    volumes:
      - ./:/var/www/shawnweb
  
  db:
    image: postgres:9.5.8
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes: 
      pgdata: